# Generated by Django 3.2.3 on 2021-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=30)),
                ('slug', models.CharField(default='Untitled', max_length=30)),
                ('page_limit', models.IntegerField(default=-1)),
                ('isFinished', models.BooleanField(default=False)),
                ('isMeta', models.BooleanField(default=False)),
                ('isPredicted', models.BooleanField(default=False)),
                ('isUserdata', models.BooleanField(default=False)),
                ('ranklist', models.TextField()),
                ('userdata', models.TextField()),
            ],
        ),
    ]
