# Generated by Django 3.2.3 on 2021-05-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='ranklist',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='userdata',
            field=models.TextField(default='null'),
        ),
    ]
