# Generated by Django 3.2.3 on 2021-05-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210523_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='isProcess',
            field=models.BooleanField(default=False),
        ),
    ]
