# Generated by Django 3.2.3 on 2021-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contest_isprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='isRanklist',
            field=models.BooleanField(default=False),
        ),
    ]
