# Generated by Django 3.2.3 on 2021-05-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contest_isranklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='userdata_progress',
            field=models.TextField(default=''),
        ),
    ]
