# Generated by Django 3.2.3 on 2021-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contest_userdata_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='userdata_begin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='userdata_progress',
            field=models.TextField(default='null'),
        ),
    ]
