# Generated by Django 3.2.3 on 2021-05-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210523_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_views', models.IntegerField(default=0)),
                ('predicitions_made', models.IntegerField(default=0)),
                ('recent_prediction', models.TextField(default='[]')),
            ],
        ),
    ]
