# Generated by Django 3.2.3 on 2021-05-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sitedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='reference',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='updates',
            field=models.TextField(default='[]'),
        ),
    ]
