# Generated by Django 3.2.3 on 2021-05-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210530_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='reference',
            field=models.TextField(default='null'),
        ),
    ]
