# Generated by Django 3.2.3 on 2021-06-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_contest_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='api_keys',
            field=models.TextField(default='[]'),
        ),
    ]
