# Generated by Django 3.2.3 on 2021-06-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contest_isprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='isFinished',
        ),
    ]
