# Generated by Django 3.2.3 on 2021-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_contest_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='any_other_headers',
            field=models.TextField(default='null'),
        ),
    ]
