# Generated by Django 3.2.3 on 2021-06-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitedata_any_other_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_prediction', models.TextField(default='[]')),
                ('demographics', models.TextField(default='{}')),
                ('active_users', models.TextField(default='{}')),
                ('predictions_heatmap', models.TextField(default='{}')),
            ],
        ),
    ]
