# Generated by Django 3.2.3 on 2021-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='page_views',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='predicitions_made',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='recent_prediction',
        ),
        migrations.AddField(
            model_name='userdata',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='predicitions_made',
            field=models.IntegerField(default=0),
        ),
    ]
