# Generated by Django 3.2.3 on 2021-06-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hashVal',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_tried_verify',
            field=models.IntegerField(default=0),
        ),
    ]
