# Generated by Django 3.2.3 on 2021-06-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210616_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_user_foresight',
            field=models.IntegerField(default=0),
        ),
    ]
