# Generated by Django 3.2.3 on 2021-06-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_profile_last_user_foresight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isBlacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='violations',
            field=models.IntegerField(default=0),
        ),
    ]
