# Generated by Django 3.2.3 on 2021-06-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_userdata_foresight_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foresights_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
