# Generated by Django 3.2.3 on 2021-06-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
