# Generated by Django 3.2.3 on 2021-06-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_team_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apikey',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
