# Generated by Django 3.2.3 on 2021-06-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_profile_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='username',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
