# Generated by Django 3.2.3 on 2021-06-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_team_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='manager',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
