# Generated by Django 3.2.3 on 2021-07-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210621_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='ranklist_begin',
            field=models.IntegerField(default=0),
        ),
    ]
