# Generated by Django 3.2.6 on 2021-08-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_contest_ranklist_begin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='ranklist_begin',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='userdata_begin',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='api_keys',
        ),
    ]
